"""Emit supabase/seed.sql (PostgreSQL) from the canonical seed data."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from backend.data import seed_data as S

def q(v):
    if v is None: return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

def arr(items):
    return "'{" + ",".join('"%s"' % i for i in items) + "}'" if items else "'{}'"

out = ["""-- =====================================================================
-- BRAHMO Rules Engine - seed data (PostgreSQL / Supabase)
-- GENERATED by scripts/generate_sql.py - edit backend/data/seed_data.py
-- Run AFTER schema.sql.
-- =====================================================================
BEGIN;

TRUNCATE audit_log, edges, knowledge_nodes, users, hierarchy_levels,
         organizations RESTART IDENTITY CASCADE;
"""]

o = S.ORGANIZATION
import json
out.append("-- Organization")
out.append("INSERT INTO organizations (id,name,segment,config) VALUES")
out.append(f"({q(o['id'])},{q(o['name'])},{q(o['segment'])},"
           f"{q(json.dumps(o['config']))});\n")

out.append("-- 15-level hierarchy DAG (20 tiers)")
out.append("INSERT INTO hierarchy_levels "
           "(id,org_id,level_number,level_name,department,parent_ids,zone) VALUES")
rows = [f"({q(i)},'supra',{n},{q(nm)},{q(d)},{arr(p)},{z})"
        for (i,n,nm,d,p,z) in S.HIERARCHY_LEVELS]
out.append(",\n".join(rows) + ";\n")

out.append("-- 7 users")
out.append("INSERT INTO users (id,org_id,name,role,department,ceiling_level,"
           "write_ceiling,compliance_clearance) VALUES")
rows = [f"({q(i)},'supra',{q(nm)},{q(r)},{q(d)},{c},"
        f"{'NULL' if w is None else w},{arr(cl)})"
        for (i,nm,r,d,c,w,cl) in S.USERS]
out.append(",\n".join(rows) + ";\n")

lvl = {l[0]: l[1] for l in S.HIERARCHY_LEVELS}
out.append("-- 50 knowledge nodes")
out.append("INSERT INTO knowledge_nodes (id,org_id,hierarchy_level_id,type,title,"
           "content,importance,zone,status,derivability_score,compliance_tags,"
           "department,hierarchy_level) VALUES")
rows = []
for (nid,hl,t,ti,co,imp,z,st,dv,tags,dept) in S.KNOWLEDGE_NODES:
    rows.append(f"({q(nid)},'supra',{q(hl)},{q(t)},{q(ti)},{q(co)},{imp},{z},"
                f"{q(st)},{dv},{arr(tags)},{q(dept)},{lvl[hl]})")
out.append(",\n".join(rows) + ";\n")

out.append("-- Typed edges")
out.append("INSERT INTO edges (source_id,target_id,edge_type) VALUES")
out.append(",\n".join(f"({q(a)},{q(b)},{q(c)})" for (a,b,c) in S.EDGES) + ";\n")

out.append("""COMMIT;

-- Verification
-- SELECT COUNT(*) FROM knowledge_nodes;   -- 50
-- SELECT COUNT(*) FROM users;             -- 7
-- SELECT COUNT(*) FROM hierarchy_levels;  -- 20
""")

path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "supabase", "seed.sql")
open(path, "w").write("\n".join(out))
print("wrote", path)
